### ISSUE TITLE
Converting to WebExtension format

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [tymofij/fb2reader#2]
Firefox now is promoting WebExtension formatted extensions, many non-WebEx addons would no longer accepted. So FB2 Reader need to convert to WebEx format.

**Comment by tymofij** [comment]
Mozilla has just implemented http response modification API, so it might be possible!
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/filterResponseData

**Comment by tymofij** [comment]
No file:// protocol support for now
https://bugzilla.mozilla.org/show_bug.cgi?id=1341341

**Comment by tymofij** [comment]
Does not work for redirects (chtyvo.org.ua uses them)
https://bugzilla.mozilla.org/show_bug.cgi?id=1376060

**Comment by KrasnayaPloshchad** [comment]
> No file:// protocol support for now

As a work around, you can create an interface to allow user opening the file from folder. EPUBReader and [Web ScrapBook](https://addons.mozilla.org/en-US/firefox/addon/web-scrapbook/) have already made it.

**Comment by tymofij** [comment]
Added support for local unzipped fb2 files with content script.
