### ISSUE TITLE
feature_request(epub): similar behavior for epub

### ISSUE THREAD

**Issue by Kristinita** [tymofij/fb2reader#5]
### 1. Summary

It would be nice, if FB2 Reader great features will be realized for [**`epub` ebooks format**](https://en.wikipedia.org/wiki/EPUB).

### 2. Argumentation

[**I don't find Firefox addon**](https://addons.mozilla.org/en-US/firefox/search/?q=epub&cat=all), which would allow reading remote `epub` documents. The addons I found work only for local `epub` documents.

### 3. Steps to reproduce

I download FB2 Reader. I download to my GitHub repository example books:

+ [**epub**](https://github.com/Kristinita/SashaBooksFormats/blob/master/DemoEpub.epub),
+ [**fb2**](https://github.com/Kristinita/SashaBooksFormats/blob/master/DemoFb2.fb2).

I open the documents [**via Jupyter nbviewer**](https://softwarerecs.stackexchange.com/a/38416/23324).

### 4. FB2 behavior

+ [**FB2**](https://nbviewer.jupyter.org/github/Kristinita/SashaBooksFormats/blob/master/DemoFb2.fb2#zz_61)

![FB2](https://i.imgur.com/ldmbgXd.png)

Excellent!

### 5. Current EPUB behavior

+ [**EPUB**](https://nbviewer.jupyter.org/github/Kristinita/SashaBooksFormats/blob/master/DemoEpub.epub)

![EPUB](https://i.imgur.com/UV4fH9A.png)

Mojibake.

Thanks.

**Comment by tymofij** [comment]
EPUB is completely different format, only similarity is that both use ZIP containers. Supporting it would be outside the scope of this extension.

And there already is https://addons.mozilla.org/en-US/firefox/addon/epubreader/

**Comment by Kristinita** [comment]
> And there already is https://addons.mozilla.org/en-US/firefox/addon/epubreader/

See item 2 of my request.

EPUBReader doesn't support remote URL's as FB2Reader.

Thanks.
