### ISSUE TITLE
Support zipped FB2 file

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [tymofij/fb2reader#6]
I just got inspiration from [Web ScrapBook](https://addons.mozilla.org/firefox/addon/web-scrapbook/), which have an ability to read zipped files, so I hope FB2 Reader can read fb2.zip file as well.

**Comment by KrasnayaPloshchad** [comment]
If you integrate one of the following JS libraries in this extension, it would help you to read plain FB2 documents form fb2.zip files.
https://stuk.github.io/jszip/
https://gildas-lormeau.github.io/zip.js/

**Comment by tymofij** [comment]
online .fb2.zip are supported now.

local .fb2.zip files are tricky because [WebRequest API does not support file:// protocol](https://bugzilla.mozilla.org/show_bug.cgi?id=1341341), and even if it did, I doubt it will get us far because of https://github.com/tymofij/fb2reader/issues/8
